language: android
android:
  components:
    - android-28
    - build-tools-27.0.3

before_install:
    - yes | sdkmanager "platforms;android-28"
    - yes | sdkmanager "build-tools;28.0.3"
    
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Run assemble and unit tests
script:
  - ./gradlew clean assembleDebug testDebug